(load "asm86.scm")
(define SYS_EXIT 1)
(define SYS_WRITE 4)
(define STDOUT 1)
(define (program)
  (load "elf.scm")
 (: 'start)
  (mov SYS_WRITE eax)
  (mov STDOUT ebx)
  (mov 'hello ecx)
  (mov 20 edx) ;Count bytes to write
  (int #x80) ;Kernel Interrupt
  (mov SYS_EXIT eax)
  (mov 0 ebx)
  (int #x80)
  (data)
 (: 'hello)
  (asciz "Hello World Sharad!\n"))
(compile program "hello" #x08048000)
